From almalinux:8
Run yum install nginx -y
Run rm -rf /usr/share/nginx/html/index.html
Add  https://getsamplefiles.com/sample-archive-files/tar#google_vignette index.html /usr/share/nginx/html
Cmd ["nginx", "-g", "daemon off;"]